### PR TITLE
feat(update): add repository url to the prompt

### PR DESCRIPTION
**Pull request by auto200**
Add formatted repository url to the update prompts
related issue: https://github.com/JamieMason/syncpack/issues/178

image

### CODE REVIEW

**Comment by JamieMason** [comment]
I'll take a look at the issue in CI, it's from [syncpack on codeclimate](https://codeclimate.com/github/JamieMason/syncpack) and nothing to do with your changes.

**Comment by auto200** [comment]
Hey @JamieMason just letting you know that I implemented some "smart" 😆 parsing of the urls and the PR is ready for You to take a look

**Comment by JamieMason** [comment]
This is great @auto200, thanks a lot. By the way, had you used [Effect](https://www.effect.website/) previously or did you figure it out as you went?

**Comment by auto200** [comment]
@JamieMason Glad you like it 😄 I did not use Effect before but gladly did not have to touch much Effect specific stuff. I **had** to look at some rxjs code in my past so pipes are _kinda_ familiar to me 😄 

The thing that wasn't clear for me was how do I actually run and test the modified code, I ended up with creating some dummy project and yarn linking the syncpack. It didn't occur to me until writing this, that I can run the built version on the syncpack's repo itself 🤣

**Comment by JamieMason** [comment]
Thanks @auto200, this is merged into the dev branch and will go out the next time I do a release 👍

**Pull request closed without merging**
