### PR TITLE
Support version overrides

### PR DESCRIPTION
**Pull request by harelmo**
Related to #63 .

@JamieMason This is an initial sketch of the proposed solution, I'd be glad to get feedback and evolve this according to any suggestions or guidelines.

Thanks 🙏

### CODE REVIEW

**Comment by JamieMason** [comment]
Appreciate it @harelmo. Just a note that I may take a little while to pick this up as my spare time is being spent working on an app, but I'll try not to keep you waiting unnecessarily.

**Comment by harelmo** [comment]
> Appreciate it @harelmo. Just a note that I may take a little while to pick this up as my spare time is being spent working on an app, but I'll try not to keep you waiting unnecessarily.

Thanks, I really appreciate it

**Comment by JamieMason** [comment]
Hey @harelmo, good news and bad news is that [6.0.0](https://github.com/JamieMason/syncpack/releases/tag/6.0.0) is released, which is a little easier to develop on and has some new features, but means a lot of conflicts for this PR 😬 .

**Comment by JamieMason** [comment]
I think one approach can potentially solve #63, #44, and #53. I'll push some tests for the use cases that have been mentioned, to be implemented later. The approach would need to support versionGroups.

**Comment by JamieMason** [comment]
This should now be possible in [6.1.0](https://github.com/JamieMason/syncpack/releases/tag/6.1.0), thanks for contributing.

**Pull request closed without merging**
