### PR TITLE
Issue 121

### PR DESCRIPTION
**Pull request by webpro**
## Description (What)

WIP. Just a heads-up I'm willing to work on it. I need to look into how scenarios and their reports work first.

### CODE REVIEW

**Comment by JamieMason** [comment]
Looking good so far Lars, thanks a lot for helping out on this. It has a scenario which is the main thing – once a scenario is in place which reproduces the problem, the rest should follow much easier. Shout any time if you need any help, `createScenario` and `mockPackage` are little builders to help make scenarios less noisy / easier to read, but they might be a bit odd or confusing, let me know.

**Comment by JamieMason** [comment]
While I remember, what makes this issue difficult is that I _think_ people that use `workspace:*` versions will tend to define them in devDependencies – so for that you want `workspace:*` to "win" when we sort version numbers. But a lot of projects will also want to reference packages from their monorepo under `dependencies` in other places – and you wouldn't want those to be changed to `workspace:*` – so that's a bug you _might_ get after fixing this.

I think people using `workspace:*` will likely need to be using version groups to get this more advanced, tuned behaviour – but I think a lot of people are expecting it to just work out the box. I'm not sure because I don't use `workspace:*` but this is my hunch.

**Comment by webpro** [comment]
Thanks, Jamie.

> While I remember, what makes this issue difficult is that I _think_ people that use `workspace:*` versions will tend to define them in devDependencies – so for that you want `workspace:*` to "win" when we sort version numbers.

Yes, this would be my expectation as well. But there currently seems to be this bug that doesn't treat two or more `workspace:*` items as equal.

> But a lot of projects will also want to reference packages from their monorepo under `dependencies` in other places – and you wouldn't want those to be changed to `workspace:*` – so that's a bug you _might_ get after fixing this.

Gotcha, good one.

> I think people using `workspace:*` will likely need to be using version groups to get this more advanced, tuned behaviour – but I think a lot of people are expecting it to just work out the box. I'm not sure because I don't use `workspace:*` but this is my hunch.

Yes, I had this expectation when I first installed syncpack yesterday. What would that configuration look like (even though perhaps not supported yet)?

**Comment by JamieMason** [comment]
> Yes, I had this expectation when I first installed syncpack yesterday. What would that configuration look like (even though perhaps not supported yet)?

The easiest way I think is something like this, it's a little manual but handles this use case:

```json
{
  "versionGroups": [
    {
      "packages": ["**"],
      "dependencies": ["each", "package", "name", "developed", "in", "this", "monorepo"],
      "dependencyTypes": ["dev"],
      "pinVersion": "workspace:*"
    }
  ]
}
```

Whenever a package developed in your monorepo is used in devDependencies, its version will be pinned at `workspace:*`. If it didn't use it in the first place, it won't be added.

**Comment by webpro** [comment]
First off, the codebase is a little bit harder to grasp for me than I expected. I have to admit the ROI here seems not worth it, especially since the more I look into things the better I realize it's more of a configuration challenge than anything. As you pointed out already. 

I think it would be hard or impossible to let syncpack fix things out of the box, since intentions are ambiguous in various cases. Large projects have exceptions everywhere and some configuration is required to unleash this powerful tool.

Now that I did this, I found that the overhead here isn't too bad, since the `workspace:*` pinning can often be combined with wildcards (such as `@org/*`) for dependencies in version groups. Here's my current setup which helped to find (and will prevent) a lot issues:

```js
module.exports = {
  versionGroups: [
    {
      label: 'Internal packages that have inconsistent version usage',
      packages: ['**'],
      dependencies: ['@org/client', '@org/cli', '@org-dev/eslint-plugin'],
      isIgnored: true, // Toggle flag or or remove group to see inconsistencies
    },
    {
      label: 'Internal dev packages are pinned to `workspace:*`',
      packages: ['**'],
      dependencies: ['@org-dev/*', '@org/types'],
      dependencyTypes: ['dev'],
      pinVersion: 'workspace:*',
    },
    {
      label: 'Internal production packages are pinned to `workspace:*`',
      packages: ['**'],
      dependencies: ['org.js', '@org/*'],
      dependencyTypes: ['prod'],
      pinVersion: 'workspace:*',
    },
    {
      label:
        'Types and internal dev packages are banned from dependencies (only allowed in devDependencies)',
      packages: ['**'],
      dependencies: ['@types/*', '*/types', '@org-dev/*'],
      dependencyTypes: ['prod'],
      isBanned: true,
    },
  ],
};
```

Note that a configuration like this also helps to separate `dependencies` (`prod`) from `devDependencies` (`dev`) properly.

This results in zero remaining issues currently so now I can keep using this to lint and fix mismatches.

Apologies for not actually contributing code after opening this draft, but at this point for me it seems not worth it to dive into this further. I do wonder how other folks would handle/consider similar situations and if you/they would agree with me.

**Comment by JamieMason** [comment]
No problem at all, thanks for trying to look into it.

As I said, this is a bit of a thorny issue and it's not obvious how to fix it, maybe it is just a userland config issue, I don't know yet for sure. 

On the codebase being hard to grasp, I suspected that would be a problem and that's on me, are you able to tell me anything that might help improve that? No problem if not. I've been using the repo to try and improve my functional programming and am using Effect.ts for the first time, that approach is probably pretty niche.

Thanks again for looking at this.

**Comment by webpro** [comment]
Nothing wrong with the approach, I simply expected less code/functionality so less time to get into the whole thing.

I'm used to glance at the code and get some idea of overall input, output, models in one way or another. How do version and semver ranges look like? When looking into "list mismatches" the "create program" doesn't give me too much here. It wasn't clear to me what I should test (TDD) and how scenarios relate to the source code (the testing approach didn't feel natural compared to how the code is organized). Perhaps a simpler test approach with less mocks, clearer fixtures and assertions closer to how the tool is being used would help. The functional approach looks efficient as a whole, but needs time until I know where to touch something to fix the failing tests. Didn't help that personally I don't really like Jest with its `console.log` hijacking approach. But all of this is just me, just one opinion.

Thanks for a great tool, really really appreciate all the efforts that went into it; sure it helps so many projects stay out of trouble.

**Comment by webpro** [comment]
For the record, my config is merged into https://github.com/kadena-community/kadena.js/blob/750d5b8c0fa69e79b5e972ec9e2b0aef51a206dd/.syncpackrc.js

For full disclosure, I've also looked at manypkg and [opened a PR for a related issue](https://github.com/Thinkmill/manypkg/pull/186), but that isn't handled yet.

**Comment by JamieMason** [comment]
Thanks @webpro, that config will be helpful when I get to writing some guides. Hoping to improve `workspace:` support soon but first I took your advice and am trying to make the tests saner, the WIP is looking more like this now: https://github.com/JamieMason/syncpack/blob/dev/src/bin-fix-mismatches/fix-mismatches.spec.ts.

**Pull request closed without merging**
