### PR TITLE
improve json-schema file

### PR DESCRIPTION
**Pull request by chaseholdren**
This PR changes some types so the generated `schema.json` file is more accurate. Before this change, `schema.json` had `DependencyType` could be an object. I tested this by running `pnpm run build:json-schema` and then uploaded the result as a gist, which I could reference from another project.

### CODE REVIEW

**Comment by JamieMason** [comment]
very nice @chaseholdren, thanks a lot!

**Comment by evaliyev** [comment]
Is this PR related to https://github.com/JamieMason/syncpack/issues/207?

**Comment by JamieMason** [comment]
This line should address that @evaliyev, I've not had chance to look deeper into what the other changes are yet but @chaseholdren may comment on those in the meantime to give us some more context.

https://github.com/JamieMason/syncpack/blob/066d2ed45cb73c4df580c1c4f58f68ecaf59fd7c/src/config/types.ts#L184-L186

**Comment by KubaJastrz** [comment]
Hello, can we push this forward somehow?

**Comment by JamieMason** [comment]
Released in [12.4.0](https://github.com/JamieMason/syncpack/releases/tag/12.4.0)

**Pull request closed without merging**
